# Generated by Django 4.0.6 on 2022-07-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='descrition',
            new_name='description',
        ),
    ]
